import { TimelineEvent } from "@/components/Timeline";

export const thursdayEvents: TimelineEvent[] = [
  {
    time: "12:00–2:00 PM",
    activity: "Board the Ship",
    location: "Miami Cruise Port",
    icon: "board",
  },
  {
    time: "Afternoon",
    activity: "Settle In",
    location: "Drop bags in the room, explore the ship, grab a drink at the bar",
    icon: "bars",
  },
  {
    time: "4:00 PM",
    activity: "Ship Sails",
    location: "Bon Voyage!",
    icon: "depart",
  },
  {
    time: "7:45 PM",
    activity: "Casino + Bar",
    location: "Casino Royale",
    icon: "casino",
    deck: "Deck 4",
  },
  {
    time: "8:30 PM",
    activity: "Group Dinner",
    location: "Main Dining Room",
    icon: "dinner",
    note: "Casual — no set theme • Deck & table TBD",
  },
  {
    time: "9:45 PM",
    activity: "Casino + Bar",
    location: "Casino Royale",
    icon: "casino",
    deck: "Deck 4",
  },
  {
    time: "10:30 PM",
    activity: "Olive or Twist Nightclub",
    location: "Resident DJ",
    icon: "party",
    deck: "Deck 14",
  },
  {
    time: "1:00 AM",
    activity: "Sorrento's Pizza",
    location: "",
    icon: "pizza",
    deck: "Deck 5",
  },
];

export const fridayEvents: TimelineEvent[] = [
  {
    time: "7:00 AM",
    activity: "Fab Abs Class",
    location: "Vitality Spa",
    icon: "abs",
    deck: "Deck 11",
    note: "30 min",
  },
  {
    time: "8:00 AM or earlier",
    activity: "Gym Session",
    location: "Vitality Spa",
    icon: "gym",
    deck: "Deck 11",
  },
  {
    time: "9:15 AM",
    activity: "Breakfast",
    location: "Windjammer",
    icon: "breakfast",
    deck: "Deck 11",
  },
  {
    time: "10:00 AM",
    activity: "Off the Ship — CocoCay",
    location: "Perfect Day at CocoCay",
    icon: "island",
    note: "Gangway opens 8 AM • All aboard 5 PM",
  },
  {
    time: "2:00 PM",
    activity: "Beach Volleyball Competition",
    location: "South Beach, CocoCay",
    icon: "volleyball",
    note: "18+",
  },
  {
    time: "4:45–6:00 PM",
    activity: "Pool Vibes w/ Resident DJ",
    location: "Poolside",
    icon: "pool",
  },
  {
    time: "5:00 PM",
    activity: "Basketball Competition",
    location: "Sports Court",
    icon: "basketball",
    deck: "Deck 13",
  },
  {
    time: "5:00–6:30 PM",
    activity: "FlowRider",
    location: "",
    icon: "flowrider",
    deck: "Deck 13",
  },
  {
    time: "6:00 PM",
    activity: "Shabbat Services",
    location: "Windjammer",
    icon: "shabbat",
    deck: "Deck 11",
  },
  {
    time: "7:45 PM",
    activity: "Casino + Bar",
    location: "Casino Royale",
    icon: "casino",
    deck: "Deck 4",
  },
  {
    time: "8:00–8:45 PM",
    activity: "Rock the Room Game Show",
    location: "Star Lounge",
    icon: "show",
    deck: "Deck 5",
  },
  {
    time: "8:30 PM",
    activity: "Group Dinner",
    location: "Main Dining Room",
    icon: "dinner",
    note: "White Night • Deck & table TBD",
  },
  {
    time: "9:45 PM",
    activity: "Casino + Bar",
    location: "Casino Royale",
    icon: "casino",
    deck: "Deck 4",
  },
  {
    time: "11:00 PM–1:00 AM",
    activity: "The Nightclub Experience",
    location: "Studio B",
    icon: "party",
    deck: "Deck 3",
  },
  {
    time: "1:00 AM",
    activity: "Sorrento's Pizza",
    location: "",
    icon: "pizza",
    deck: "Deck 5",
  },
];

export const saturdayEvents: TimelineEvent[] = [
  {
    time: "7:00 AM",
    activity: "Fab Abs Class",
    location: "Vitality Spa",
    icon: "abs",
    deck: "Deck 11",
    note: "30 min",
  },
  {
    time: "8:00 AM or earlier",
    activity: "Gym Session",
    location: "Vitality Spa",
    icon: "gym",
    deck: "Deck 11",
  },
  {
    time: "9:15 AM",
    activity: "Breakfast",
    location: "Windjammer",
    icon: "breakfast",
    deck: "Deck 11",
  },
  {
    time: "Daytime",
    activity: "Bimini",
    location: "On the island",
    icon: "island",
    note: "Gangway opens 8:30 AM • All aboard by 4:30 PM",
  },
  {
    time: "4:30 PM",
    activity: "Ship Leaves Bimini",
    location: "",
    icon: "depart",
  },
  {
    time: "4:45 PM",
    activity: "Basketball Free-Throw Competition",
    location: "Sports Court",
    icon: "basketball",
    deck: "Deck 13",
  },
  {
    time: "7:00–7:30 PM",
    activity: "60 Seconds or Less Game Show",
    location: "Star Lounge",
    icon: "show",
    deck: "Deck 5",
  },
  {
    time: "7:30 PM",
    activity: "Tequila Tasting",
    location: "Port Merchants",
    icon: "tequila",
    deck: "Deck 5",
  },
  {
    time: "7:45 PM",
    activity: "Casino + Bar",
    location: "Casino Royale",
    icon: "casino",
    deck: "Deck 4",
  },
  {
    time: "8:15 PM",
    activity: "Group Dinner",
    location: "Main Dining Room",
    icon: "dinner",
    note: "White Night • Deck & table TBD",
  },
  {
    time: "9:45 PM",
    activity: "Casino + Bar",
    location: "Casino Royale",
    icon: "casino",
    deck: "Deck 4",
  },
  {
    time: "11:30 PM–1:30 AM",
    activity: "Olive or Twist Nightclub",
    location: "Resident DJ",
    icon: "party",
    deck: "Deck 14",
  },
  {
    time: "1:30 AM",
    activity: "Sorrento's Pizza",
    location: "",
    icon: "pizza",
    deck: "Deck 5",
  },
];

export const sundayEvents: TimelineEvent[] = [
  {
    time: "7:00 AM",
    activity: "Fab Abs Class",
    location: "Vitality Spa",
    icon: "abs",
    deck: "Deck 11",
    note: "30 min",
  },
  {
    time: "8:00 AM or earlier",
    activity: "Gym Session",
    location: "Vitality Spa",
    icon: "gym",
    deck: "Deck 11",
  },
  {
    time: "9:15 AM",
    activity: "Breakfast",
    location: "Windjammer",
    icon: "breakfast",
    deck: "Deck 11",
  },
  {
    time: "11:00 AM",
    activity: "Pickleball Competition",
    location: "Sports Court",
    icon: "pickleball",
    deck: "Deck 13",
    note: "18+",
  },
  {
    time: "12:00–3:30 PM",
    activity: "Boogie Boarding",
    location: "FlowRider",
    icon: "flowrider",
    deck: "Deck 13",
  },
  {
    time: "1:00 PM",
    activity: "Belly Flop Contest",
    location: "Poolside",
    icon: "splash",
    deck: "Deck 11",
  },
  {
    time: "1:45–2:15 PM",
    activity: "Battle of the Sexes",
    location: "Star Lounge",
    icon: "show",
    deck: "Deck 5",
  },
  {
    time: "2:00–3:00 PM",
    activity: "Love & Marriage Game Show",
    location: "Royal Theater",
    icon: "show",
    deck: "Deck 3",
  },
  {
    time: "3:00–4:00 PM",
    activity: "Volleyball Competition",
    location: "Sports Court",
    icon: "volleyball",
    deck: "Deck 13",
    note: "18+",
  },
  {
    time: "4:30–5:30 PM",
    activity: "Dodgeball Competition",
    location: "Sports Court",
    icon: "dodgeball",
    deck: "Deck 13",
    note: "18+",
  },
  {
    time: "6:00 PM",
    activity: "Knockout Basketball Competition",
    location: "Sports Court",
    icon: "basketball",
    deck: "Deck 13",
  },
  {
    time: "7:45 PM",
    activity: "Casino + Bar",
    location: "Casino Royale",
    icon: "casino",
    deck: "Deck 4",
  },
  {
    time: "8:15 PM",
    activity: "Group Dinner",
    location: "Main Dining Room",
    icon: "dinner",
    note: "Dress Your Best • Deck & table TBD",
  },
  {
    time: "9:45 PM",
    activity: "Casino + Bar",
    location: "Casino Royale",
    icon: "casino",
    deck: "Deck 4",
  },
  {
    time: "10:30–11:15 PM",
    activity: "Late Night Comedy Show",
    location: "Royal Theater",
    icon: "comedy",
    deck: "Deck 3",
  },
  {
    time: "10:30–11:30 PM",
    activity: "Silent Toga Party",
    location: "Olive or Twist",
    icon: "party",
    deck: "Deck 14",
    note: "Toga!",
  },
  {
    time: "11:30 PM–1:30 AM",
    activity: "Olive or Twist Nightclub",
    location: "Resident DJ",
    icon: "party",
    deck: "Deck 14",
  },
  {
    time: "1:30 AM",
    activity: "Sorrento's Pizza",
    location: "",
    icon: "pizza",
    deck: "Deck 5",
  },
];

export const mondayEvents: TimelineEvent[] = [
  {
    time: "6:00 AM",
    activity: "Arrive Miami",
    location: "",
    icon: "arrive",
  },
  {
    time: "7:30 AM",
    activity: "Deboard the Ship",
    location: "Miami Cruise Terminal",
    icon: "deboard",
  },
];
